sensors:
   - name: CPU
     type: temperature
     interval_ms: 100
     method: iio
     device: coretemp
     channel: temp3
     attribute: input
   - name: NVME
     type: temperature
     interval_ms: 1000
     method: file
     device: /sys/class/hwmon/hwmon2/temp1_input