sensors:
   - name: CPU
     type: temperature
     method: iio
     device: coretemp
     channel: temp3
     attribute: input
   - name: NVME
     type: temperature
     method: file
     device: /sys/class/hwmon/hwmon2/temp1_input